### ISSUE TITLE
[BUG] Tutorial: potentially incorrect log path

### ISSUE THREAD

**Issue by richlv** [mjstarrett/Landmarks#12]
https://github.com/mjstarrett/Landmarks/wiki/Open-a-functional-Navigation-Experiment says the logs will be saved in "/data/tmp/test.log" - the leading slash probably could be dropped, and at least with Unity 2019.4.40f1 the path is "editor-data/" (no further subdirectories).

Don't think I can supply pull requests for the Github wiki, only creating the issue.

**Comment by mjstarrett** [comment]
Updated wiki text to be more generic regarding the location of editor data.
