### ISSUE TITLE
[BUG] Tutorial: non-existent file referenced

### ISSUE THREAD

**Issue by richlv** [mjstarrett/Landmarks#13]
https://github.com/mjstarrett/Landmarks/wiki/Add-new-tasks-to-an-existing-Landmarks-compatible-environment says:
"open Assets/Landmarks/Scenes/SimpleSample_50x50.unity"

Unfortunately, that file does not seem to exist:
https://github.com/mjstarrett/Landmarks/tree/master/Assets/Landmarks/Scenes

**Comment by richlv** [comment]
I have mostly recreated this file as per https://github.com/mjstarrett/Landmarks/wiki/Create-a-Landmarks-compatible-Environment-from-scratch (with a few differences or missing bits as per #14), happy to share it if useful.

**Comment by mjstarrett** [comment]
The scene is now located in Assets/Landmarks/Scenes/demo as 'demo_SimpleSample_50x50.unity. All other references to the scene appear correct; updated this text to match.

**Comment by richlv** [comment]
Hi, thank you so much for looking into this.
I might be misunderstanding the intent, but it seems like the "demo_SimpleSample_50x50.unity" and "SimpleSample_50x50.unity" files are supposed to be different.

In https://github.com/mjstarrett/Landmarks/wiki/Add-new-tasks-to-an-existing-Landmarks-compatible-environment, we are adding "TASK_LearnTargets" and "TASK_NavigationTask", but "demo_SimpleSample_50x50.unity" already has all this added.
