### ISSUE TITLE
[BUG] Tutorial: "Create ... from scratch" issues

### ISSUE THREAD

**Issue by richlv** [mjstarrett/Landmarks#14]
Potential issues in https://github.com/mjstarrett/Landmarks/wiki/Create-a-Landmarks-compatible-Environment-from-scratch :

### Simple changes

"Click on the existing filler_props GameObject." -> "Right click..."
"In the project window, navigate to Assets/Landmarks/Materials/" -> ..."/Materials/SimpleSampleScene/" (this change needed several times in the document)
"...Transform component of the Y GameObject" - in the "Position->Z" field, value "3.8147e" is shown - presumably this is truncated scientific notation value, perhaps should be 0?
"To persistent startup locations for each target" -> probably should be "To set persistent startup locations for each target"

### Missing file
"...navigate to Assets/Landmarks/Materials/ then drag and drop the SimpleSample_MarbleFloor..." - there doesn't seem to be any resource named "SimpleSample_MarbleFloor", nothing with "marblefloor" in the name.

The demo scene seems to use "Assets/Free Assets/Prototype Materials/Materials/M-Marble".

### Other issues
When adding target objects, they are way off from the walled area - this seems to be caused by "filler_props" having position of 0/0/0, but "TargetObjects" - 0/0/700
Could this be https://github.com/mjstarrett/Landmarks/blob/5142b20d76871a7409df188b189a4cfe26988b5f/Assets/Landmarks/Prefabs/_Landmarks_.prefab#L5622C15-L5622C15 ?
Given that a few steps later, at "To randomly populate targets at startup", we're supposed to set "TargetObjects" to 0/0/700, it looks like the default in prefabs has accidentally been already set to 700.

Several screenshots have values with many decimal places, most also seem to be trimmed (for example, 7.89999, 0.09999, -0.6699 etc). Might be useful to clarify on these.

Step 7 instructs to add three starting locations, but there's already one "StartLocation01" from prefab. Would be great to clarify what, if anything, should be done with it.

**Comment by mjstarrett** [comment]
Language was changed from specific material files to indicate any material the user would like. The transform values and their decimal-places seem like fairly minor details and users can just modify these to suit their needs.

**Comment by richlv** [comment]
Thank you so much for looking into this, greatly appreciated.
Admittedly, the very specific instructions seemed great, as they were easier to follow for a complete newbie, and they allowed to recreate the exact demo scene.
The latest version doesn't recommend going to Assets/Landmarks/Materials/ , and I would have struggled to figure out where and what exactly to grab from.
I'd be happy to provide exact instructions (perhaps with a couple of files moved around), but if that's not desirable - not a big problem at all :)

Regarding the transform values, I was thinking about a simple clarifying sentence, recommending to use "0" or other round values. Also happy to provide updated screenshots (although it could be less consistent, as there are minor visual differences in the UI).
