### ISSUE TITLE
[BUG] Build settings contain many deleted scenes out of the box

### ISSUE THREAD

**Issue by richlv** [mjstarrett/Landmarks#21]
Landmarks git clone from today.

Open Landmarks project, load the demo scene, open build settings - there are many deleted scenes included.
<img width="860" alt="image" src="https://github.com/mjstarrett/Landmarks/assets/112888/f1b67595-4b2b-4700-b0c4-f3c850ff230d">

**Comment by mjstarrett** [comment]
You can just delete them. I'll wipe them from the list in a future commit.

**Comment by richlv** [comment]
Thank you, looks great in the latest commit.

For the record, the issue was made more tricky because more recent Unity LTS versions failed upon build when there were deleted scenes included.
Selecting one selected all deleted scenes, and deleting didn't do anything... to them all - it actually deleted only one entry. With that many deleted scenes, this was hidden behind the scrollbar, and it seemed that it is impossible to delete them at all.
Ended up using a custom script as per https://stackoverflow.com/a/57043642/272387 .
Not really needed right now, but maybe of some use when/if supported Unity version is updated.
