### ISSUE TITLE
[BUG] Unused features built in

### ISSUE THREAD

**Issue by richlv** [mjstarrett/Landmarks#22]
Landmark checkout as of today.
When cresting a build, it looks like VR features are always included, even when not intended to be used at all. In my case, that takes a very long time - not including unused features would significantly cut down on the build time.
Perhaps it would also reduce the build size.

Example phases during the build that seem to be VR related ("vr_glove_color_red"):

![image](https://github.com/mjstarrett/Landmarks/assets/112888/6529f2b2-9295-47b0-86fb-b4c2438631dd)
![image](https://github.com/mjstarrett/Landmarks/assets/112888/4555c822-5923-4bdd-9237-28d0a80b56e8)

**Comment by mjstarrett** [comment]
The VR features are referenced in some of the core scripts of Landmarks, so they do need to be included in the build. New features are in development to allow users to select the user interface on startup, which requires having those assets ready and available for use. The builds shouldn't be taking more than a few minutes, and you really only need to build when you are ready to start piloting participants (i.e., you can do internal testing straight from the Unity editor when you are making lots of small changes during initial development).

**Comment by richlv** [comment]
Noted, thank you. Indeed, was mostly testing from the editor's "play" view, but did various repeated builds to test the HUD issue in builds, and the "vr" phases took most of the time.

**Comment by richlv** [comment]
To expand on the build time - I have a problem where the build does not use widescreen as expected, and the HUD is cropped (although it could just be something I messed up myself).
Playing with Unity settings, re-built it a dozen times, and the build time was a noticeable factor :)

Understandably, this is not a critical issue - but in a longer run, shorter build times can lead to better results.
