### ISSUE TITLE
Start Location Rotation

### ISSUE THREAD

**Issue by SR-gituser** [mjstarrett/Landmarks#25]
**Please describe your issue.**
A navigation task was setup containing one target, with several trial repeats and multiple start locations.
However, after the target is found, and the player is positioned at the new start position for the subsequent trial, the start position contains the new start position (x,y,z), but retains the same rotation as the end of previous trial (when the target was located and the players position is frozen). I'm not sure if this is by design or whether there's something potentially causing this. 

**Describe the solution you'd like**
I was hoping to reset the rotation when a new start positioned is assigned; according to the rotation parameter specified in the start location parameters.

**Comment by mjstarrett** [comment]
@SR-gituser, Thanks for pointing this out. Please re-open the issue if the fix does not work or reach out if you have any questions/issues with the fix. The MovePlayer.cs script is better set up to handle CharacterController's and FirstPersonController's unwillingness to be moved or rotated, respectively.

**Comment by SR-gituser** [comment]
The issue was corrected with the update. Landmarks is a great tool, much appreciated.
